### PR TITLE
probation data-engineering terraform-backend

### PR DESCRIPTION
**Pull request by davidbridgwood**
# Pull Request Objective

This piece of work is being tracked in
[this](https://github.com/ministryofjustice/analytical-platform-data-engineering/issues/769)
GitHub Issue.

create buckets in `analytical-platform-data-engineering-sandbox-a` and `analytical-platform-data-engineering-production` for the probation data-engineering team to store their terraform state. This is to aid in the migration of [analytical-platform-data-engineering](https://github.com/ministryofjustice/analytical-platform-data-engineering) from pulumi to terraform.

## Checklist

> [!NOTE]
> Each items should be checked. Skipping below checks could delay your PR review!

- [x] I have reviewed the [style guide](https://docs.analytical-platform.service.justice.gov.uk/documentation/platform/infrastructure/terraform.html#terraform)
and ensured that my code complies with it
- [ ] All checks have passed (or override label applied, if I've
used the `override-static-analysis` label, I've explained why)
- [ ] I have self-reviewed my code
- [ ] I have reviewed the checks and can attest they're as expected

### Additional Comments

`oidc-roles.tf` needed changing as the dynamic blocks were causing duplicates with the same Sid which the terraform plan was complaining about. I've updated so the multiple statements/buckets (when present) get added to the same Sid.
The plan looks a bit strange but i'm pretty sure its only adding the buckets i've added and is just getting mixed up with the statement names. But would be good for someone more familiar to check!

### CODE REVIEW

**Comment by davidbridgwood** [comment]
I'm not seeing the buckets i've added in any plan on the checks - is there anything more I need to add?

**Review by jacobwoffenden — COMMENTED** [review]
@davidbridgwood do you have any design documents and/or ADRs for your Terraform deployment?

**Comment by davidbridgwood** [comment]
> @davidbridgwood do you have any design documents and/or ADRs for your Terraform deployment?

@jacobwoffenden - we don't no. If you have some examples you can point to happy to put something together.

**Comment by jacobwoffenden** [comment]
> > @davidbridgwood do you have any design documents and/or ADRs for your Terraform deployment?
> 
> @jacobwoffenden - we don't no. If you have some examples you can point to happy to put something together.

I was wondering if you'd thought more about my suggestion in [this](https://mojdt.slack.com/archives/C06TFT94JTC/p1727343320531429) thread, we can give you out of the box state management and account access instead of rolling your own

**Pull request closed without merging**
