### PR TITLE
🛂 cjs-dashboard-app GitHub Actions role

### LINKED ISSUE #2951: ✨ Create new OIDC role for GitHub runner
### Describe the feature request.

As a Developer of the CJS Dashboard App
I want to connect to the Analytical Platform via GitHub Runners
So I can run an integration test which requires access to a specific bucket.

Technical notes: 
- This is the [repo](https://github.com/ministryofjustice/cjs_scorecard_exploratory_analysis) in which the GitHub runners run on and will need access to the `mojap-cjs-dashboard` bucket.
- We need an OICD role which can be assumed by a GitHub runner, that has sufficient permissions to access and read the data in the above bucket.

### Describe the context.

_No response_

### Value / Purpose

So that we can run an Integration Test - improve the quality/level  of testing.

### User Types

_No response_

### PR DESCRIPTION
**Pull request by jacobwoffenden**
This pull request:

- Resolves #2951
- Adds a new component for cjs-dashboard-app in analytical-platform-data-production
- Adds a policy and role to allow `ministryofjustice/cjs_scorecard_exploratory_analysis` access to `arn:aws:s3:::mojap-cjs-dashboard`

Note(s) for the reviewer:

- I did briefly explore adding this into <https://github.com/ministryofjustice/data-platform/blob/main/terraform/aws/analytical-platform/oidc/oidc-roles.tf>, however I am unsure if that code allows for specifying granular policy statements other than just allowing the subject to assume either `github-actions-infrastructure` or `data-engineering-infrastructure`, which allow usage of the `AdministratorAccess` policy
- Based on the above, a separate (or update to the existing) component might be more appropriate for hosting these policies and roles, however I've created a new one like we did for `create-a-derived-table`, but we should look at consolidating them longer term #2976

Signed-off-by: Jacob Woffenden <jacob.woffenden@digital.justice.gov.uk>

### CODE REVIEW

**Comment by michaeljcollinsuk** [comment]
Not a blocker to this, but out of interest do we know how the bucket `mojap-cjs-dashboard` was created/is managed? As does not appear to have been created in control panel (as does not have the `alpha` prefix and does not appear in the UI) and also cannot find reference to it being defined in terraform.

**Review by michaeljcollinsuk — APPROVED** [review]
LGTM

**Review by julialawrence — APPROVED** [review]
LGTM

**Comment by laura-auburn** [comment]
> Not a blocker to this, but out of interest do we know how the bucket mojap-cjs-dashboard was created/is managed? As does not appear to have been created in control panel (as does not have the alpha prefix and does not appear in the UI) and also cannot find reference to it being defined in terraform.

Sorry was just taking a look at this PR as I lead on the CJS dashboard and not sure if anyone responded to your question @michaeljcollinsuk. The bucket was created/is managed by the [data engineering exports](https://github.com/moj-analytical-services/data-engineering-exports) repo as a [pull dataset](https://github.com/moj-analytical-services/data-engineering-exports/blob/main/pull_datasets/cjs_dashboard.yaml). This was required as we needed the bucket to sit on the AP but with its contents visible to a specific external user (our cloud platform app).

**Pull request merged**
