### PR TITLE
📐 C4 diagram updates

### PR DESCRIPTION
**Pull request by bagg3rs**
# Pull Request Objective

This PR adds missing descriptions to systems, updates arrow directions (up for debate 🙃 ) clears up relationships and moves future c4 under new section

### CODE REVIEW

**Comment by SoumayaMauthoorMOJ** [comment]
@bagg3rs any chance you can move quicksight to the left, so that's it's closer to the other visualisation tools?

**Comment by bagg3rs** [comment]
> @bagg3rs any chance you can move quicksight to the left, so that's it's closer to the other visualisation tools?

@SoumayaMauthoorMOJ Changed colour also and put in relationship for user viewing 
https://github.com/ministryofjustice/analytical-platform/pull/5300/commits/e7fb98bc58f725e469ab976f16f72ebf436cc29c

**Comment by SoumayaMauthoorMOJ** [comment]
What colour change? oh wait do you mean the colour for the metrics layer?

**Review by SoumayaMauthoorMOJ — DISMISSED** [review]

**Review by julialawrence — APPROVED** [review]
Nice!

**Pull request merged**
