### PR TITLE
♻️ Replace TDT with 11ty

### PR DESCRIPTION
**Pull request by hrahim-moj**
~Added 11ty prototype for testing as Data Platform 'front door'/hosting user-facing content.~

This pull request replaces GDS' technical documentation template with 11ty, which will serve as the front-door for Data Platform

# TODO:
- [x] Decide on domain `data-platform.service.justice.gov.uk` vs. `www.data-platform.service.justice.gov.uk`
  - www. follows the product page pattern from GOV.UK Pay/Notify/Forms/One Login
- [x] Decide on whether we use GDS Transport
- [x] Find a new home for ways of working
- [x] Find a new home for internal technical guides (containers, developing, Terraform, etc.)
- [ ] Add publishing job

### CODE REVIEW

**Comment by hrahim-moj** [comment]
> ~Added 11ty prototype for testing as Data Platform 'front door'/hosting user-facing content.~
> 
> This pull request replaces GDS' technical documentation template with 11ty, which will serve as the front-door for Data Platform
> 
> # TODO:
> * [x]  Decide on domain `data-platform.service.justice.gov.uk` vs. `www.data-platform.service.justice.gov.uk`
>   
>   * [www](http://www). follows the product page pattern from GOV.UK Pay/Notify/Forms/One Login
> * [x]  Decide on whether we use GDS Transport
> * [x]  Find a new home for ways of working
> * [x]  Find a new home for internal technical guides (containers, developing, Terraform, etc.)
> * [ ]  Add publishing job

@jacobwoffenden 
* Let's go with www if that's the pattern those other sites follow
* According to the [design system](https://design-system.service.gov.uk/styles/typography/) we must use the Transport font if we're a service.gov.uk domain (but unsure if we can if we're service.justice.gov.uk) - will ask around
* Just caught up with @bagg3rs - ways of working and internal technical guides to go on a separate eleventy instance (Tech Docs with ADRs and arch docs and diagrams can remain on this instance as they may be of interest to users)
* Publishing job TBD

**Comment by bagg3rs** [comment]
@hrahim-moj yes other P&A teams follow the team is main repo and user guidance is a separate repo much like AP. 

e.g. Cloud Platform and OpsEng just did a similar split
- User = https://user-guide.cloud-platform.service.justice.gov.uk/
- Team https://runbooks.cloud-platform.service.justice.gov.uk/#cloud-platform-runbooks

**Comment by hrahim-moj** [comment]
@bagg3rs Since the user guidance is part of the front door, what's the best way to go about the split? Is it okay for team docs to be in the other repo?

**Comment by bagg3rs** [comment]
Create a new repo for front door/guidance as team docs need to be as close to infrastructure and config code.

We can setup another repo next week and port across anything we need

**Comment by jacobwoffenden** [comment]
This has been moved to https://github.com/ministryofjustice/data-platform-user-guidance

**Pull request closed without merging**
