### PR TITLE
Remove team member jh

### PR DESCRIPTION
**Pull request by tom-webber**
😢

### CODE REVIEW

**Review by BrianEllwood — DISMISSED** [review]
lgtm

**Comment by Gary-H9** [comment]
Should we remove from [here](https://github.com/ministryofjustice/data-platform/blob/8424e2c76f5774972470802102c312286767d1f4/terraform/pagerduty/teams.tf#L13) too?

**Review by julialawrence — APPROVED** [review]
Lgtm

**Review by jacobwoffenden — APPROVED** [review]

**Pull request merged**
